// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info/info.proto

package info

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnvironmentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvironmentRequest) Reset()         { *m = EnvironmentRequest{} }
func (m *EnvironmentRequest) String() string { return proto.CompactTextString(m) }
func (*EnvironmentRequest) ProtoMessage()    {}
func (*EnvironmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3955287c00436ed0, []int{0}
}

func (m *EnvironmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentRequest.Unmarshal(m, b)
}
func (m *EnvironmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentRequest.Marshal(b, m, deterministic)
}
func (m *EnvironmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentRequest.Merge(m, src)
}
func (m *EnvironmentRequest) XXX_Size() int {
	return xxx_messageInfo_EnvironmentRequest.Size(m)
}
func (m *EnvironmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentRequest proto.InternalMessageInfo

type EnvironmentResponse struct {
	GoRoot               string   `protobuf:"bytes,1,opt,name=go_root,json=goRoot,proto3" json:"go_root,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	HostName             string   `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	NetInterface         string   `protobuf:"bytes,4,opt,name=net_interface,json=netInterface,proto3" json:"net_interface,omitempty"`
	Goarch               string   `protobuf:"bytes,5,opt,name=goarch,proto3" json:"goarch,omitempty"`
	Goos                 string   `protobuf:"bytes,6,opt,name=goos,proto3" json:"goos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvironmentResponse) Reset()         { *m = EnvironmentResponse{} }
func (m *EnvironmentResponse) String() string { return proto.CompactTextString(m) }
func (*EnvironmentResponse) ProtoMessage()    {}
func (*EnvironmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3955287c00436ed0, []int{1}
}

func (m *EnvironmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentResponse.Unmarshal(m, b)
}
func (m *EnvironmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentResponse.Marshal(b, m, deterministic)
}
func (m *EnvironmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentResponse.Merge(m, src)
}
func (m *EnvironmentResponse) XXX_Size() int {
	return xxx_messageInfo_EnvironmentResponse.Size(m)
}
func (m *EnvironmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentResponse proto.InternalMessageInfo

func (m *EnvironmentResponse) GetGoRoot() string {
	if m != nil {
		return m.GoRoot
	}
	return ""
}

func (m *EnvironmentResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *EnvironmentResponse) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *EnvironmentResponse) GetNetInterface() string {
	if m != nil {
		return m.NetInterface
	}
	return ""
}

func (m *EnvironmentResponse) GetGoarch() string {
	if m != nil {
		return m.Goarch
	}
	return ""
}

func (m *EnvironmentResponse) GetGoos() string {
	if m != nil {
		return m.Goos
	}
	return ""
}

func init() {
	proto.RegisterType((*EnvironmentRequest)(nil), "EnvironmentRequest")
	proto.RegisterType((*EnvironmentResponse)(nil), "EnvironmentResponse")
}

func init() { proto.RegisterFile("info/info.proto", fileDescriptor_3955287c00436ed0) }

var fileDescriptor_3955287c00436ed0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x40,
	0x0c, 0x86, 0xad, 0xae, 0x5d, 0x37, 0x2a, 0x42, 0x76, 0xd1, 0x41, 0x2f, 0x52, 0x2f, 0x9e, 0x2a,
	0xe8, 0x13, 0x78, 0x10, 0xd9, 0x8b, 0x48, 0x5f, 0xa0, 0xd4, 0x25, 0xed, 0xce, 0xa1, 0xf9, 0xd7,
	0x99, 0xb8, 0x8f, 0xe6, 0xf3, 0x49, 0x07, 0x0a, 0x15, 0xbd, 0x84, 0xfc, 0xdf, 0x1f, 0x48, 0xfe,
	0xd0, 0x85, 0xd7, 0x16, 0x0f, 0x43, 0x29, 0x77, 0x01, 0x86, 0x62, 0x45, 0xfc, 0xa2, 0x7b, 0x1f,
	0xa0, 0xbd, 0xa8, 0x55, 0xf2, 0xf9, 0x25, 0xd1, 0x8a, 0xef, 0x8c, 0x96, 0xbf, 0x70, 0xdc, 0x41,
	0xa3, 0xf0, 0x15, 0xcd, 0x3b, 0xd4, 0x01, 0x30, 0x97, 0xdd, 0x66, 0xf7, 0x8b, 0x2a, 0xef, 0x50,
	0x01, 0xc6, 0x8e, 0xe6, 0x7b, 0x09, 0xd1, 0x43, 0xdd, 0x61, 0x32, 0x46, 0xc9, 0x37, 0xb4, 0xd8,
	0x22, 0x5a, 0xad, 0x4d, 0x2f, 0xee, 0x28, 0x79, 0x27, 0x03, 0x78, 0x6b, 0x7a, 0xe1, 0x3b, 0x3a,
	0x57, 0xb1, 0xda, 0xab, 0x49, 0x68, 0x9b, 0x8d, 0xb8, 0x59, 0x1a, 0x38, 0x53, 0xb1, 0xf5, 0xc8,
	0xf8, 0x92, 0xf2, 0x0e, 0x4d, 0xd8, 0x6c, 0xdd, 0xf1, 0xb8, 0x73, 0x50, 0xcc, 0x34, 0xeb, 0x80,
	0xe8, 0xf2, 0x44, 0x53, 0xff, 0xf8, 0x4e, 0xa7, 0x93, 0xbb, 0xf9, 0x99, 0xf8, 0x55, 0x6c, 0x42,
	0xd6, 0xda, 0x82, 0x97, 0xe5, 0xdf, 0xc8, 0xd7, 0xab, 0xf2, 0x9f, 0xc0, 0xc5, 0xc1, 0x47, 0x9e,
	0xfe, 0xf4, 0xf4, 0x13, 0x00, 0x00, 0xff, 0xff, 0xee, 0x79, 0x02, 0x7c, 0x3a, 0x01, 0x00, 0x00,
}
